# Generated by Django 5.1.4 on 2025-01-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0002_assessmentcategory_attendancepolicy_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
