# Generated by Django 5.1.4 on 2025-01-06 11:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0003_alter_subscription_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent',
        ),
        migrations.AddField(
            model_name='student',
            name='parent_contact_info',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_emergency_contact',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_first_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_last_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_occupation',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_relationship',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.CreateModel(
            name='StudentRegistrationPin',
            fields=[
                ('pin_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.school')),
            ],
            options={
                'unique_together': {('school', 'otp')},
            },
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
