# Generated by Django 5.1.4 on 2025-01-09 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0004_remove_student_parent_student_parent_contact_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistrationpin',
            name='otp',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='studentregistrationpin',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_pins', to='user_registration.school'),
        ),
    ]
