# Generated by Django 5.1.4 on 2025-01-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0007_remove_student_class_arm_remove_student_class_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
