# Generated by Django 5.1.4 on 2025-01-17 12:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0008_year_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='classteacher',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_teachers', to='user_registration.school'),
        ),
        migrations.AddField(
            model_name='term',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentClassAndSubjectAssignment',
            fields=[
                ('assignment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_arm_assignments', to='user_registration.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='user_registration.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_and_subject_assignments', to='user_registration.student')),
                ('subjects', models.ManyToManyField(related_name='student_subject_assignments', to='user_registration.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='user_registration.term')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='user_registration.year')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectRegistrationControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_control', to='user_registration.school')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('timetable_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='user_registration.school')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.JSONField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='user_registration.teacher')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_timetables', to='user_registration.timetable')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.JSONField()),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='user_registration.class')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_timetables', to='user_registration.timetable')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentClassAssignment',
        ),
    ]
