# Generated by Django 5.1.4 on 2025-03-04 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0011_remove_subject_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherassignment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_assignments', to='user_registration.department'),
        ),
    ]
