# Generated by Django 5.1.4 on 2025-03-16 21:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0013_remove_teacherassignment_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectClass',
            fields=[
                ('subject_class_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_class', to='user_registration.classyear')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_class', to='user_registration.department')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_class', to='user_registration.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_class', to='user_registration.subject')),
            ],
        ),
    ]
