# Generated by Django 5.1.4 on 2025-03-16 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0014_subjectclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectclass',
            name='class_year',
        ),
    ]
