# Generated by Django 5.1.4 on 2025-03-29 23:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0016_remove_teacherassignment_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDepartment',
            fields=[
                ('subject_class_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_department', to='user_registration.class')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_department', to='user_registration.department')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_department', to='user_registration.school')),
            ],
        ),
    ]
