# Generated by Django 5.1.4 on 2025-03-30 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0017_classdepartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='class_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='user_registration.classdepartment'),
        ),
    ]
