# Generated by Django 5.1.4 on 2025-04-05 18:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0018_alter_student_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('student_class_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_class', to='user_registration.classdepartment')),
                ('class_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_class', to='user_registration.classyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_class', to='user_registration.student')),
            ],
        ),
    ]
