# Generated by Django 5.1.4 on 2025-04-16 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0019_studentclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_students', to='user_registration.school'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_subscriptions', to='user_registration.school'),
        ),
        migrations.AlterUniqueTogether(
            name='studentclass',
            unique_together={('student', 'class_year', 'class_arm')},
        ),
    ]
