# Generated by Django 5.1.4 on 2025-04-17 22:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0020_alter_student_school_alter_subscription_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expected_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='number_students',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StudentSubjectRegistration',
            fields=[
                ('registration_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_registrations', to='user_registration.school')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_registrations', to='user_registration.studentclass')),
                ('subject_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_registrations', to='user_registration.subjectclass')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_registrations', to='user_registration.term')),
            ],
            options={
                'verbose_name': 'Student Subject Registration',
                'verbose_name_plural': 'Student Subject Registrations',
                'unique_together': {('student_class', 'subject_class', 'term')},
            },
        ),
        migrations.DeleteModel(
            name='StudentClassAndSubjectAssignment',
        ),
    ]
