# Generated by Django 5.1.4 on 2025-04-20 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0021_alter_subscription_expected_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualresult',
            name='class_assigned',
        ),
        migrations.RemoveField(
            model_name='annualresult',
            name='school',
        ),
        migrations.RemoveField(
            model_name='annualresult',
            name='student',
        ),
        migrations.RemoveField(
            model_name='annualresult',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='annualresult',
            name='year',
        ),
        migrations.RemoveField(
            model_name='assessmentcategory',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='continuousassessment',
            name='class_assigned',
        ),
        migrations.RemoveField(
            model_name='continuousassessment',
            name='school',
        ),
        migrations.RemoveField(
            model_name='continuousassessment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='continuousassessment',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='continuousassessment',
            name='term',
        ),
        migrations.RemoveField(
            model_name='continuousassessment',
            name='year',
        ),
        migrations.RemoveField(
            model_name='examscore',
            name='class_assigned',
        ),
        migrations.RemoveField(
            model_name='examscore',
            name='school',
        ),
        migrations.RemoveField(
            model_name='examscore',
            name='student',
        ),
        migrations.RemoveField(
            model_name='examscore',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='examscore',
            name='term',
        ),
        migrations.RemoveField(
            model_name='examscore',
            name='year',
        ),
        migrations.RemoveField(
            model_name='result',
            name='class_assigned',
        ),
        migrations.RemoveField(
            model_name='result',
            name='school',
        ),
        migrations.RemoveField(
            model_name='result',
            name='student',
        ),
        migrations.RemoveField(
            model_name='result',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='result',
            name='term',
        ),
        migrations.RemoveField(
            model_name='result',
            name='year',
        ),
        migrations.RemoveField(
            model_name='scoreobtainedperassessment',
            name='class_assigned',
        ),
        migrations.RemoveField(
            model_name='scoreobtainedperassessment',
            name='school',
        ),
        migrations.RemoveField(
            model_name='scoreobtainedperassessment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='scoreobtainedperassessment',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='scoreobtainedperassessment',
            name='term',
        ),
        migrations.RemoveField(
            model_name='scoreobtainedperassessment',
            name='year',
        ),
        migrations.RemoveField(
            model_name='scoreperassessmentinstance',
            name='class_assigned',
        ),
        migrations.RemoveField(
            model_name='scoreperassessmentinstance',
            name='school',
        ),
        migrations.RemoveField(
            model_name='scoreperassessmentinstance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='scoreperassessmentinstance',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='scoreperassessmentinstance',
            name='term',
        ),
        migrations.RemoveField(
            model_name='scoreperassessmentinstance',
            name='year',
        ),
        migrations.AddField(
            model_name='annualresult',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_results', to='user_registration.studentsubjectregistration'),
        ),
        migrations.AddField(
            model_name='continuousassessment',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='continuous_assessments', to='user_registration.studentsubjectregistration'),
        ),
        migrations.AddField(
            model_name='examscore',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_scores', to='user_registration.studentsubjectregistration'),
        ),
        migrations.AddField(
            model_name='result',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='user_registration.studentsubjectregistration'),
        ),
        migrations.AddField(
            model_name='scoreobtainedperassessment',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='total_assessment_scores', to='user_registration.studentsubjectregistration'),
        ),
        migrations.AddField(
            model_name='scoreperassessmentinstance',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_scores', to='user_registration.studentsubjectregistration'),
        ),
        migrations.AlterField(
            model_name='annualresult',
            name='annual_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annualresult',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examscore',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='scoreperassessmentinstance',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_scores', to='user_registration.assessmentcategory'),
        ),
        migrations.CreateModel(
            name='AnnualResultWeightConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_term_weight', models.FloatField(default=0.3333333333333333)),
                ('second_term_weight', models.FloatField(default=0.3333333333333333)),
                ('third_term_weight', models.FloatField(default=0.3333333333333333)),
                ('class_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.classyear')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.department')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_weights', to='user_registration.school')),
            ],
            options={
                'unique_together': {('school', 'class_year', 'department')},
            },
        ),
        migrations.CreateModel(
            name='GradingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.FloatField()),
                ('max_score', models.FloatField()),
                ('grade', models.CharField(max_length=5)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_systems', to='user_registration.school')),
            ],
            options={
                'ordering': ['-max_score'],
            },
        ),
        migrations.CreateModel(
            name='ResultConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ca_score', models.FloatField(default=30)),
                ('total_exam_score', models.FloatField(default=70)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_configuration', to='user_registration.school')),
            ],
        ),
        migrations.CreateModel(
            name='ResultVisibilityControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_result_open', models.BooleanField(default=False)),
                ('annual_result_open', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_visibility_control', to='user_registration.school')),
            ],
        ),
        migrations.DeleteModel(
            name='ExamCategory',
        ),
    ]
