# Generated by Django 5.1.4 on 2025-04-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0022_remove_annualresult_class_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualresult',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubjectregistration',
            name='class_arm_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentsubjectregistration',
            name='class_year_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
