# Generated by Django 5.1.4 on 2025-04-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0023_annualresult_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultconfiguration',
            name='pass_mark',
            field=models.FloatField(default=50),
        ),
    ]
