# Generated by Django 5.1.4 on 2025-04-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0024_resultconfiguration_pass_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladmin',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
