# Generated by Django 5.1.4 on 2025-04-29 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0025_schooladmin_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superadmin',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schooladmin',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
