# Generated by Django 5.1.4 on 2025-08-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0028_alter_school_email_school_unique_school_name_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceverification',
            name='accreditation_certificates',
            field=models.FileField(upload_to='compliance/accreditation/'),
        ),
        migrations.AlterField(
            model_name='complianceverification',
            name='proof_of_registration',
            field=models.FileField(upload_to='compliance/registration/'),
        ),
    ]
