# Generated by Django 5.1.4 on 2025-08-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0029_alter_complianceverification_accreditation_certificates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceverification',
            name='accreditation_certificates',
            field=models.ImageField(upload_to='compliance/accreditation/'),
        ),
        migrations.AlterField(
            model_name='complianceverification',
            name='proof_of_registration',
            field=models.ImageField(upload_to='compliance/registration/'),
        ),
    ]
