# Generated by Django 5.1.4 on 2025-08-23 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0031_remove_attendanceflag_class_assigned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherassignment',
            old_name='class_assigned',
            new_name='class_department_assigned',
        ),
        migrations.RenameField(
            model_name='teacherassignment',
            old_name='subject',
            new_name='subject_class',
        ),
    ]
