# Generated by Django 5.1.4 on 2025-09-18 23:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0032_rename_class_assigned_teacherassignment_class_department_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceverification',
            name='last_updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='complianceverification',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
