# Generated by Django 5.1.4 on 2025-10-05 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_registration", "0033_complianceverification_last_updated_on_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentclass",
            unique_together={("student", "klass")},
        ),
        migrations.AddField(
            model_name="studentclass",
            name="klass",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_classes",
                to="user_registration.class",
            ),
        ),
        migrations.AlterField(
            model_name="studentclass",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_classes",
                to="user_registration.student",
            ),
        ),
        migrations.RemoveField(
            model_name="studentclass",
            name="class_arm",
        ),
        migrations.RemoveField(
            model_name="studentclass",
            name="class_year",
        ),
    ]
