# Generated by Django 5.1.4 on 2025-10-05 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_registration", "0034_alter_studentclass_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentclass",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="studentclass",
            name="class_arm",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_classes",
                to="user_registration.class",
            ),
        ),
        migrations.AddField(
            model_name="studentclass",
            name="class_year",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_classes",
                to="user_registration.classyear",
            ),
        ),
        migrations.AddField(
            model_name="studentclass",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name="studentclass",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("student",),
                name="uniq_active_student_assignment",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentclass",
            constraint=models.UniqueConstraint(
                fields=("student", "class_year", "class_arm"),
                name="uniq_student_year_arm",
            ),
        ),
        migrations.RemoveField(
            model_name="studentclass",
            name="klass",
        ),
    ]
